In [ ]:
import pandas as pd

In [ ]:
### 데이터 불러오기
data = pd.read_csv('rawdata.csv')


### '공용량', '현재수위' 교체
팔당댐 = pd.read_csv('팔당댐_수정.csv', encoding='cp949')
data[팔당댐.columns[1:3]] = 팔당댐.iloc[:, 1:3]

### '한강대교_유량', '청담대교_유량' 교체
한강대교_유량 = pd.read_csv('한강대교_유량.csv')
data['한강대교_유량'] = 한강대교_유량['한강대교_유량']

청담대교_유량 = pd.read_csv('청담대교_유량_0822.csv', encoding='cp949')
data['청담대교_유량'] = 청담대교_유량.iloc[:, 2]

### 수위 column 4개, '행주대교_유량' 교체
수위_행주유량 = pd.read_csv('수위4개_행주대교유량.csv', encoding='cp949')
data[수위_행주유량.columns[1:]] = 수위_행주유량.iloc[:, 1:]


### '방류량_시간차' 추가
방류량_시간차 = pd.read_csv('방류량_시간차_수정.csv', encoding='cp949')
data['방류량_시간차'] = 방류량_시간차

### '강화대교_조위_시간차' 추가
강화대교_시간차 = pd.read_csv('강화대교조위_시간차.csv', encoding='cp949')
data['강화대교_조위_시간차'] = 강화대교_시간차

### '서울시 강수량' 추가
서울시강수량 = pd.read_csv('서울시강수량.csv')
data['서울시강수량'] = 서울시강수량


### 불필요한 column 버리기
data.drop(['유입량', '저수량', '방류량', '잠수교_유량', '대곡교_강수량', '진관교_강수량', '송정동_강수량', '강화대교_조위'],
          axis=1, inplace=True)

### Index 처리
data.set_index('날짜', drop=True, inplace=True)
data

,현재수위,공용량,청담대교_유량,한강대교_유량,행주대교_유량,청담대교_수위,잠수교_수위,한강대교_수위,행주대교_수위,방류량_시간차,강화대교_조위_시간차,서울시강수량
날짜,,,,,,,,,,,,
2012-05-01 00:00,24.800,24.93,469.05,729.80,540.18,310.7,300.2,290.0,275.3,575.70,193.0,0.0
2012-05-01 00:10,24.794,25.15,498.00,731.48,540.18,314.7,300.2,290.0,275.3,575.30,199.0,0.0
2012-05-01 00:20,24.789,25.31,490.68,726.42,540.18,313.7,301.2,290.0,275.3,555.00,207.0,0.0
2012-05-01 00:30,24.789,25.31,476.21,726.42,552.17,311.7,301.2,290.0,276.3,575.70,215.0,0.0
2012-05-01 00:40,24.789,25.31,476.21,707.17,564.29,311.7,301.2,291.0,277.3,575.40,226.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-07-18 23:10,25.040,31.14,319.84,-456.41,974.40,0.0,0.0,0.0,0.0,258.67,407.0,0.0
2022-07-18 23:20,25.040,31.14,314.01,-717.30,1006.88,0.0,0.0,0.0,0.0,258.58,431.0,0.0
2022-07-18 23:30,25.040,31.14,387.55,-843.37,1039.90,0.0,0.0,0.0,0.0,258.56,453.0,0.0
2022-07-18 23:40,25.040,31.14,454.91,-1023.37,1073.46,0.0,0.0,0.0,0.0,258.65,476.0,0.0
2022-07-18 23:50,25.040,31.14,582.21,-1049.44,1090.45,0.0,0.0,0.0,0.0,258.09,499.0,0.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 276336 entries, 2012-05-01 00:00 to 2022-07-18 23:50
Data columns (total 12 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   현재수위         276336 non-null  float64
 1   공용량          276336 non-null  float64
 2   청담대교_유량      276336 non-null  float64
 3   한강대교_유량      276336 non-null  float64
 4   행주대교_유량      276336 non-null  float64
 5   청담대교_수위      276336 non-null  float64
 6   잠수교_수위       276336 non-null  float64
 7   한강대교_수위      276336 non-null  float64
 8   행주대교_수위      276336 non-null  float64
 9   방류량_시간차      276336 non-null  float64
 10  강화대교_조위_시간차  276336 non-null  float64
 11  서울시강수량       276336 non-null  float64
dtypes: float64(12)
memory usage: 27.4+ MB

In [ ]:
# data.to_csv('newdata.csv', encoding='cp949')