In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings(action='ignore')

import time
from glob import glob
from tqdm import tqdm
import os

import tensorflow as tf
import tensorflow.keras as keras
from keras.models import Sequential, Model
from keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, TensorBoard
from keras import backend as K
# from keras.utils import plot_model

from keras.layers import Activation, Dense, LSTM, GRU, Bidirectional, AveragePooling1D, GlobalAveragePooling1D, Dropout, Flatten, BatchNormalization, TimeDistributed, Input, Reshape, RepeatVector, Concatenate, GlobalMaxPooling1D 
from keras.layers.convolutional import Conv1D, MaxPooling1D, AveragePooling1D


#GPU 자원이 부족
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession
config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)

In [4]:
광진교_수위 = pd.read_csv('/content/drive/MyDrive/신입기수 프로젝트/Dataset/광진교수위.csv')

In [5]:
광진교_수위

                       Date    수위
0       2012-05-01 00:00:00   1.2
1       2012-05-01 00:10:00   1.2
2       2012-05-01 00:20:00   1.2
3       2012-05-01 00:30:00   1.2
4       2012-05-01 00:40:00   1.2
...                     ...   ...
276331  2022-07-18 23:10:00  1.12
276332  2022-07-18 23:20:00  1.12
276333  2022-07-18 23:30:00  1.12
276334  2022-07-18 23:40:00  1.12
276335  2022-07-18 23:50:00  1.12

[276336 rows x 2 columns]

In [6]:
광진교_수위.isnull().sum()

Date    0
수위      0
dtype: int64